// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const getUserByEmployeeID = `-- name: GetUserByEmployeeID :one
SELECT id, employee_id, name, password_hash, role, created_at, updated_at
FROM users
WHERE employee_id = $1
`

func (q *Queries) GetUserByEmployeeID(ctx context.Context, employeeID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmployeeID, employeeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
