// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counts.sql

package db

import (
	"context"
	"database/sql"
)

const countByMaterial = `-- name: CountByMaterial :one


SELECT COUNT(*) AS total
FROM purchase_records
WHERE material_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type CountByMaterialParams struct {
	MaterialCode string       `json:"material_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// counts.sql
// COUNT(*) queries matching each of the 7 filter combinations in search.sql.
// Used by the search handler to compute pagination metadata (total_records,
// total_pages) without fetching the full result set.
//
// Parameter layout mirrors search.sql exactly — only LIMIT/OFFSET and ORDER BY
// are omitted, since COUNT(*) returns a single row.
//
//	Single-filter queries:
//	  $1 = filter value
//	  sqlc.narg('start_date') = optional lower bound on purchase_date
//	  sqlc.narg('end_date')   = optional upper bound on purchase_date
//
//	Two-filter queries:
//	  $1 = first filter value
//	  $2 = second filter value
//	  sqlc.narg('start_date'), sqlc.narg('end_date')
//
//	Three-filter query:
//	  $1 = material_code
//	  $2 = vendor_code
//	  $3 = plant_code
//	  sqlc.narg('start_date'), sqlc.narg('end_date')
//
// ============================================================
// 1. MATERIAL ONLY
// ============================================================
func (q *Queries) CountByMaterial(ctx context.Context, arg CountByMaterialParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByMaterial, arg.MaterialCode, arg.StartDate, arg.EndDate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByMaterialPlant = `-- name: CountByMaterialPlant :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type CountByMaterialPlantParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 5. MATERIAL + PLANT
// ============================================================
func (q *Queries) CountByMaterialPlant(ctx context.Context, arg CountByMaterialPlantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByMaterialPlant,
		arg.MaterialCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByMaterialVendor = `-- name: CountByMaterialVendor :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type CountByMaterialVendorParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 4. MATERIAL + VENDOR
// ============================================================
func (q *Queries) CountByMaterialVendor(ctx context.Context, arg CountByMaterialVendorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByMaterialVendor,
		arg.MaterialCode,
		arg.VendorCode,
		arg.StartDate,
		arg.EndDate,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByMaterialVendorPlant = `-- name: CountByMaterialVendorPlant :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
`

type CountByMaterialVendorPlantParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 7. MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) CountByMaterialVendorPlant(ctx context.Context, arg CountByMaterialVendorPlantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByMaterialVendorPlant,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByPlant = `-- name: CountByPlant :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE plant_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type CountByPlantParams struct {
	PlantCode string       `json:"plant_code"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

// ============================================================
// 3. PLANT ONLY
// ============================================================
func (q *Queries) CountByPlant(ctx context.Context, arg CountByPlantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByPlant, arg.PlantCode, arg.StartDate, arg.EndDate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByVendor = `-- name: CountByVendor :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE vendor_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type CountByVendorParams struct {
	VendorCode string       `json:"vendor_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

// ============================================================
// 2. VENDOR ONLY
// ============================================================
func (q *Queries) CountByVendor(ctx context.Context, arg CountByVendorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByVendor, arg.VendorCode, arg.StartDate, arg.EndDate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countByVendorPlant = `-- name: CountByVendorPlant :one

SELECT COUNT(*) AS total
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type CountByVendorPlantParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

// ============================================================
// 6. VENDOR + PLANT
// ============================================================
func (q *Queries) CountByVendorPlant(ctx context.Context, arg CountByVendorPlantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByVendorPlant,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}
