// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type PurchaseRecord struct {
	ID             int64          `json:"id"`
	PlantCode      string         `json:"plant_code"`
	MaterialCode   string         `json:"material_code"`
	VendorCode     string         `json:"vendor_code"`
	Description    sql.NullString `json:"description"`
	PurchaseNo     sql.NullString `json:"purchase_no"`
	PurchaseDate   time.Time      `json:"purchase_date"`
	NetPrice       sql.NullString `json:"net_price"`
	Cost           sql.NullString `json:"cost"`
	SupplyingPlant sql.NullString `json:"supplying_plant"`
	Quantity       sql.NullString `json:"quantity"`
	Currency       sql.NullString `json:"currency"`
	Unit           sql.NullString `json:"unit"`
}

type User struct {
	ID           int64          `json:"id"`
	EmployeeID   string         `json:"employee_id"`
	Name         sql.NullString `json:"name"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
