// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"database/sql"
)

const searchByMaterialCostAsc = `-- name: SearchByMaterialCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost ASC
LIMIT $2 OFFSET $3
`

type SearchByMaterialCostAscParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialCostAsc(ctx context.Context, arg SearchByMaterialCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialCostAsc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialCostDesc = `-- name: SearchByMaterialCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost DESC
LIMIT $2 OFFSET $3
`

type SearchByMaterialCostDescParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialCostDesc(ctx context.Context, arg SearchByMaterialCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialCostDesc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialNetPriceAsc = `-- name: SearchByMaterialNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price ASC
LIMIT $2 OFFSET $3
`

type SearchByMaterialNetPriceAscParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialNetPriceAsc(ctx context.Context, arg SearchByMaterialNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialNetPriceAsc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialNetPriceDesc = `-- name: SearchByMaterialNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price DESC
LIMIT $2 OFFSET $3
`

type SearchByMaterialNetPriceDescParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialNetPriceDesc(ctx context.Context, arg SearchByMaterialNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialNetPriceDesc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantCostAsc = `-- name: SearchByMaterialPlantCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantCostAscParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPlantCostAsc(ctx context.Context, arg SearchByMaterialPlantCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantCostAsc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantCostDesc = `-- name: SearchByMaterialPlantCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantCostDescParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPlantCostDesc(ctx context.Context, arg SearchByMaterialPlantCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantCostDesc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantNetPriceAsc = `-- name: SearchByMaterialPlantNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantNetPriceAscParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPlantNetPriceAsc(ctx context.Context, arg SearchByMaterialPlantNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantNetPriceAsc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantNetPriceDesc = `-- name: SearchByMaterialPlantNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantNetPriceDescParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPlantNetPriceDesc(ctx context.Context, arg SearchByMaterialPlantNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantNetPriceDesc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantPurchaseDateAsc = `-- name: SearchByMaterialPlantPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantPurchaseDateAscParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 5. MATERIAL + PLANT
// ============================================================
func (q *Queries) SearchByMaterialPlantPurchaseDateAsc(ctx context.Context, arg SearchByMaterialPlantPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantPurchaseDateAsc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPlantPurchaseDateDesc = `-- name: SearchByMaterialPlantPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialPlantPurchaseDateDescParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPlantPurchaseDateDesc(ctx context.Context, arg SearchByMaterialPlantPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPlantPurchaseDateDesc,
		arg.MaterialCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPurchaseDateAsc = `-- name: SearchByMaterialPurchaseDateAsc :many


SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date ASC
LIMIT $2 OFFSET $3
`

type SearchByMaterialPurchaseDateAscParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// search.sql
// Parameterised SELECT queries for all 7 filter combinations × 3 sort columns × 2 directions = 42 queries.
// Each query supports an optional date range via nullable parameters using sqlc.narg().
// LIMIT/OFFSET pagination is applied to every query.
//
// Parameter layout per query:
//
//	Filter-only queries (single filter):
//	  $1 = filter value
//	  $2 = start_date (nullable date)
//	  $3 = end_date   (nullable date)
//	  $4 = limit
//	  $5 = offset
//
//	Filter-only queries (two filters):
//	  $1 = first filter value
//	  $2 = second filter value
//	  $3 = start_date (nullable date)
//	  $4 = end_date   (nullable date)
//	  $5 = limit
//	  $6 = offset
//
//	Filter-only queries (three filters):
//	  $1 = material_code
//	  $2 = vendor_code
//	  $3 = plant_code
//	  $4 = start_date (nullable date)
//	  $5 = end_date   (nullable date)
//	  $6 = limit
//	  $7 = offset
//
// The handler selects the correct query based on the active filter set and the
// requested sort_by + sort_order values (allowed-value switch in Go).
// NULL start_date / end_date means "no lower / upper bound on purchase_date".
// ============================================================
// 1. MATERIAL ONLY
// ============================================================
func (q *Queries) SearchByMaterialPurchaseDateAsc(ctx context.Context, arg SearchByMaterialPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPurchaseDateAsc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialPurchaseDateDesc = `-- name: SearchByMaterialPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date DESC
LIMIT $2 OFFSET $3
`

type SearchByMaterialPurchaseDateDescParams struct {
	MaterialCode string       `json:"material_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialPurchaseDateDesc(ctx context.Context, arg SearchByMaterialPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialPurchaseDateDesc,
		arg.MaterialCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorCostAsc = `-- name: SearchByMaterialVendorCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorCostAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorCostAsc(ctx context.Context, arg SearchByMaterialVendorCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorCostAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorCostDesc = `-- name: SearchByMaterialVendorCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorCostDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorCostDesc(ctx context.Context, arg SearchByMaterialVendorCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorCostDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorNetPriceAsc = `-- name: SearchByMaterialVendorNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorNetPriceAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorNetPriceAsc(ctx context.Context, arg SearchByMaterialVendorNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorNetPriceAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorNetPriceDesc = `-- name: SearchByMaterialVendorNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorNetPriceDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorNetPriceDesc(ctx context.Context, arg SearchByMaterialVendorNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorNetPriceDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantCostAsc = `-- name: SearchByMaterialVendorPlantCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY cost ASC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantCostAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPlantCostAsc(ctx context.Context, arg SearchByMaterialVendorPlantCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantCostAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantCostDesc = `-- name: SearchByMaterialVendorPlantCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY cost DESC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantCostDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPlantCostDesc(ctx context.Context, arg SearchByMaterialVendorPlantCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantCostDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantNetPriceAsc = `-- name: SearchByMaterialVendorPlantNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY net_price ASC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantNetPriceAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPlantNetPriceAsc(ctx context.Context, arg SearchByMaterialVendorPlantNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantNetPriceAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantNetPriceDesc = `-- name: SearchByMaterialVendorPlantNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY net_price DESC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantNetPriceDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPlantNetPriceDesc(ctx context.Context, arg SearchByMaterialVendorPlantNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantNetPriceDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantPurchaseDateAsc = `-- name: SearchByMaterialVendorPlantPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY purchase_date ASC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantPurchaseDateAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 7. MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) SearchByMaterialVendorPlantPurchaseDateAsc(ctx context.Context, arg SearchByMaterialVendorPlantPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantPurchaseDateAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPlantPurchaseDateDesc = `-- name: SearchByMaterialVendorPlantPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($6::date IS NULL OR purchase_date >= $6::date)
  AND ($7::date   IS NULL OR purchase_date <= $7::date)
ORDER BY purchase_date DESC
LIMIT $4 OFFSET $5
`

type SearchByMaterialVendorPlantPurchaseDateDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPlantPurchaseDateDesc(ctx context.Context, arg SearchByMaterialVendorPlantPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPlantPurchaseDateDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPurchaseDateAsc = `-- name: SearchByMaterialVendorPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date ASC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorPurchaseDateAscParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

// ============================================================
// 4. MATERIAL + VENDOR
// ============================================================
func (q *Queries) SearchByMaterialVendorPurchaseDateAsc(ctx context.Context, arg SearchByMaterialVendorPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPurchaseDateAsc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByMaterialVendorPurchaseDateDesc = `-- name: SearchByMaterialVendorPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date DESC
LIMIT $3 OFFSET $4
`

type SearchByMaterialVendorPurchaseDateDescParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	Limit        int32        `json:"limit"`
	Offset       int32        `json:"offset"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByMaterialVendorPurchaseDateDesc(ctx context.Context, arg SearchByMaterialVendorPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByMaterialVendorPurchaseDateDesc,
		arg.MaterialCode,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantCostAsc = `-- name: SearchByPlantCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost ASC
LIMIT $2 OFFSET $3
`

type SearchByPlantCostAscParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByPlantCostAsc(ctx context.Context, arg SearchByPlantCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantCostAsc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantCostDesc = `-- name: SearchByPlantCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost DESC
LIMIT $2 OFFSET $3
`

type SearchByPlantCostDescParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByPlantCostDesc(ctx context.Context, arg SearchByPlantCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantCostDesc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantNetPriceAsc = `-- name: SearchByPlantNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price ASC
LIMIT $2 OFFSET $3
`

type SearchByPlantNetPriceAscParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByPlantNetPriceAsc(ctx context.Context, arg SearchByPlantNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantNetPriceAsc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantNetPriceDesc = `-- name: SearchByPlantNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price DESC
LIMIT $2 OFFSET $3
`

type SearchByPlantNetPriceDescParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByPlantNetPriceDesc(ctx context.Context, arg SearchByPlantNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantNetPriceDesc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantPurchaseDateAsc = `-- name: SearchByPlantPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date ASC
LIMIT $2 OFFSET $3
`

type SearchByPlantPurchaseDateAscParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

// ============================================================
// 3. PLANT ONLY
// ============================================================
func (q *Queries) SearchByPlantPurchaseDateAsc(ctx context.Context, arg SearchByPlantPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantPurchaseDateAsc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByPlantPurchaseDateDesc = `-- name: SearchByPlantPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE plant_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date DESC
LIMIT $2 OFFSET $3
`

type SearchByPlantPurchaseDateDescParams struct {
	PlantCode string       `json:"plant_code"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByPlantPurchaseDateDesc(ctx context.Context, arg SearchByPlantPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlantPurchaseDateDesc,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorCostAsc = `-- name: SearchByVendorCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost ASC
LIMIT $2 OFFSET $3
`

type SearchByVendorCostAscParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorCostAsc(ctx context.Context, arg SearchByVendorCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorCostAsc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorCostDesc = `-- name: SearchByVendorCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY cost DESC
LIMIT $2 OFFSET $3
`

type SearchByVendorCostDescParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorCostDesc(ctx context.Context, arg SearchByVendorCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorCostDesc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorNetPriceAsc = `-- name: SearchByVendorNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price ASC
LIMIT $2 OFFSET $3
`

type SearchByVendorNetPriceAscParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorNetPriceAsc(ctx context.Context, arg SearchByVendorNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorNetPriceAsc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorNetPriceDesc = `-- name: SearchByVendorNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY net_price DESC
LIMIT $2 OFFSET $3
`

type SearchByVendorNetPriceDescParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorNetPriceDesc(ctx context.Context, arg SearchByVendorNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorNetPriceDesc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantCostAsc = `-- name: SearchByVendorPlantCostAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost ASC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantCostAscParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPlantCostAsc(ctx context.Context, arg SearchByVendorPlantCostAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantCostAsc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantCostDesc = `-- name: SearchByVendorPlantCostDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY cost DESC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantCostDescParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPlantCostDesc(ctx context.Context, arg SearchByVendorPlantCostDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantCostDesc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantNetPriceAsc = `-- name: SearchByVendorPlantNetPriceAsc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price ASC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantNetPriceAscParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPlantNetPriceAsc(ctx context.Context, arg SearchByVendorPlantNetPriceAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantNetPriceAsc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantNetPriceDesc = `-- name: SearchByVendorPlantNetPriceDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY net_price DESC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantNetPriceDescParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPlantNetPriceDesc(ctx context.Context, arg SearchByVendorPlantNetPriceDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantNetPriceDesc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantPurchaseDateAsc = `-- name: SearchByVendorPlantPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date ASC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantPurchaseDateAscParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

// ============================================================
// 6. VENDOR + PLANT
// ============================================================
func (q *Queries) SearchByVendorPlantPurchaseDateAsc(ctx context.Context, arg SearchByVendorPlantPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantPurchaseDateAsc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPlantPurchaseDateDesc = `-- name: SearchByVendorPlantPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($5::date IS NULL OR purchase_date >= $5::date)
  AND ($6::date   IS NULL OR purchase_date <= $6::date)
ORDER BY purchase_date DESC
LIMIT $3 OFFSET $4
`

type SearchByVendorPlantPurchaseDateDescParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPlantPurchaseDateDesc(ctx context.Context, arg SearchByVendorPlantPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPlantPurchaseDateDesc,
		arg.VendorCode,
		arg.PlantCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPurchaseDateAsc = `-- name: SearchByVendorPurchaseDateAsc :many

SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date ASC
LIMIT $2 OFFSET $3
`

type SearchByVendorPurchaseDateAscParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

// ============================================================
// 2. VENDOR ONLY
// ============================================================
func (q *Queries) SearchByVendorPurchaseDateAsc(ctx context.Context, arg SearchByVendorPurchaseDateAscParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPurchaseDateAsc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByVendorPurchaseDateDesc = `-- name: SearchByVendorPurchaseDateDesc :many
SELECT id, plant_code, material_code, vendor_code, description,
       purchase_no, purchase_date, net_price, cost,
       supplying_plant, quantity, currency, unit
FROM purchase_records
WHERE vendor_code = $1
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
ORDER BY purchase_date DESC
LIMIT $2 OFFSET $3
`

type SearchByVendorPurchaseDateDescParams struct {
	VendorCode string       `json:"vendor_code"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) SearchByVendorPurchaseDateDesc(ctx context.Context, arg SearchByVendorPurchaseDateDescParams) ([]PurchaseRecord, error) {
	rows, err := q.db.QueryContext(ctx, searchByVendorPurchaseDateDesc,
		arg.VendorCode,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRecord
	for rows.Next() {
		var i PurchaseRecord
		if err := rows.Scan(
			&i.ID,
			&i.PlantCode,
			&i.MaterialCode,
			&i.VendorCode,
			&i.Description,
			&i.PurchaseNo,
			&i.PurchaseDate,
			&i.NetPrice,
			&i.Cost,
			&i.SupplyingPlant,
			&i.Quantity,
			&i.Currency,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
