// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package db

import (
	"context"
	"database/sql"
)

const materialSubSummaryMaterial = `-- name: MaterialSubSummaryMaterial :one


SELECT
    pr.material_code,
    MAX(pr.description)                                                    AS description,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND ($2::date IS NULL OR pr.purchase_date >= $2::date)
  AND ($3::date   IS NULL OR pr.purchase_date <= $3::date)
GROUP BY pr.material_code
`

type MaterialSubSummaryMaterialParams struct {
	MaterialCode string       `json:"material_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type MaterialSubSummaryMaterialRow struct {
	MaterialCode        string         `json:"material_code"`
	Description         interface{}    `json:"description"`
	AvgCost             float64        `json:"avg_cost"`
	AvgNetPrice         float64        `json:"avg_net_price"`
	LastPurchaseCost    sql.NullString `json:"last_purchase_cost"`
	MinCost             interface{}    `json:"min_cost"`
	DistinctVendorCount int64          `json:"distinct_vendor_count"`
	DistinctPlantCount  int64          `json:"distinct_plant_count"`
	PurchaseOrderCount  int64          `json:"purchase_order_count"`
	Currencies          interface{}    `json:"currencies"`
	Units               interface{}    `json:"units"`
	EarliestDate        interface{}    `json:"earliest_date"`
	LatestDate          interface{}    `json:"latest_date"`
}

// ============================================================
// SECTION C: MATERIAL SUB-SUMMARY QUERIES
// Returns per-material aggregate metrics including description.
// Returned columns: material_code, description, avg_cost, avg_net_price,
//
//	last_purchase_cost, min_cost, distinct_vendor_count, distinct_plant_count,
//	purchase_order_count, currencies, units, earliest_date, latest_date
//
// ============================================================
// ============================================================
// C.1 MATERIAL ONLY
// ============================================================
func (q *Queries) MaterialSubSummaryMaterial(ctx context.Context, arg MaterialSubSummaryMaterialParams) (MaterialSubSummaryMaterialRow, error) {
	row := q.db.QueryRowContext(ctx, materialSubSummaryMaterial, arg.MaterialCode, arg.StartDate, arg.EndDate)
	var i MaterialSubSummaryMaterialRow
	err := row.Scan(
		&i.MaterialCode,
		&i.Description,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const materialSubSummaryMaterialPlant = `-- name: MaterialSubSummaryMaterialPlant :one

SELECT
    pr.material_code,
    MAX(pr.description)                                                    AS description,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.plant_code    = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.plant_code    = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.material_code
`

type MaterialSubSummaryMaterialPlantParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type MaterialSubSummaryMaterialPlantRow struct {
	MaterialCode        string         `json:"material_code"`
	Description         interface{}    `json:"description"`
	AvgCost             float64        `json:"avg_cost"`
	AvgNetPrice         float64        `json:"avg_net_price"`
	LastPurchaseCost    sql.NullString `json:"last_purchase_cost"`
	MinCost             interface{}    `json:"min_cost"`
	DistinctVendorCount int64          `json:"distinct_vendor_count"`
	DistinctPlantCount  int64          `json:"distinct_plant_count"`
	PurchaseOrderCount  int64          `json:"purchase_order_count"`
	Currencies          interface{}    `json:"currencies"`
	Units               interface{}    `json:"units"`
	EarliestDate        interface{}    `json:"earliest_date"`
	LatestDate          interface{}    `json:"latest_date"`
}

// ============================================================
// C.3 MATERIAL + PLANT
// ============================================================
func (q *Queries) MaterialSubSummaryMaterialPlant(ctx context.Context, arg MaterialSubSummaryMaterialPlantParams) (MaterialSubSummaryMaterialPlantRow, error) {
	row := q.db.QueryRowContext(ctx, materialSubSummaryMaterialPlant,
		arg.MaterialCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i MaterialSubSummaryMaterialPlantRow
	err := row.Scan(
		&i.MaterialCode,
		&i.Description,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const materialSubSummaryMaterialVendor = `-- name: MaterialSubSummaryMaterialVendor :one

SELECT
    pr.material_code,
    MAX(pr.description)                                                    AS description,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.vendor_code   = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.vendor_code   = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.material_code
`

type MaterialSubSummaryMaterialVendorParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type MaterialSubSummaryMaterialVendorRow struct {
	MaterialCode        string         `json:"material_code"`
	Description         interface{}    `json:"description"`
	AvgCost             float64        `json:"avg_cost"`
	AvgNetPrice         float64        `json:"avg_net_price"`
	LastPurchaseCost    sql.NullString `json:"last_purchase_cost"`
	MinCost             interface{}    `json:"min_cost"`
	DistinctVendorCount int64          `json:"distinct_vendor_count"`
	DistinctPlantCount  int64          `json:"distinct_plant_count"`
	PurchaseOrderCount  int64          `json:"purchase_order_count"`
	Currencies          interface{}    `json:"currencies"`
	Units               interface{}    `json:"units"`
	EarliestDate        interface{}    `json:"earliest_date"`
	LatestDate          interface{}    `json:"latest_date"`
}

// ============================================================
// C.2 MATERIAL + VENDOR
// ============================================================
func (q *Queries) MaterialSubSummaryMaterialVendor(ctx context.Context, arg MaterialSubSummaryMaterialVendorParams) (MaterialSubSummaryMaterialVendorRow, error) {
	row := q.db.QueryRowContext(ctx, materialSubSummaryMaterialVendor,
		arg.MaterialCode,
		arg.VendorCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i MaterialSubSummaryMaterialVendorRow
	err := row.Scan(
		&i.MaterialCode,
		&i.Description,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const materialSubSummaryMaterialVendorPlant = `-- name: MaterialSubSummaryMaterialVendorPlant :one

SELECT
    pr.material_code,
    MAX(pr.description)                                                    AS description,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.vendor_code   = $2
       AND sub.plant_code    = $3
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.vendor_code   = $2
  AND pr.plant_code    = $3
  AND ($4::date IS NULL OR pr.purchase_date >= $4::date)
  AND ($5::date   IS NULL OR pr.purchase_date <= $5::date)
GROUP BY pr.material_code
`

type MaterialSubSummaryMaterialVendorPlantParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type MaterialSubSummaryMaterialVendorPlantRow struct {
	MaterialCode        string         `json:"material_code"`
	Description         interface{}    `json:"description"`
	AvgCost             float64        `json:"avg_cost"`
	AvgNetPrice         float64        `json:"avg_net_price"`
	LastPurchaseCost    sql.NullString `json:"last_purchase_cost"`
	MinCost             interface{}    `json:"min_cost"`
	DistinctVendorCount int64          `json:"distinct_vendor_count"`
	DistinctPlantCount  int64          `json:"distinct_plant_count"`
	PurchaseOrderCount  int64          `json:"purchase_order_count"`
	Currencies          interface{}    `json:"currencies"`
	Units               interface{}    `json:"units"`
	EarliestDate        interface{}    `json:"earliest_date"`
	LatestDate          interface{}    `json:"latest_date"`
}

// ============================================================
// C.4 MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) MaterialSubSummaryMaterialVendorPlant(ctx context.Context, arg MaterialSubSummaryMaterialVendorPlantParams) (MaterialSubSummaryMaterialVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, materialSubSummaryMaterialVendorPlant,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i MaterialSubSummaryMaterialVendorPlantRow
	err := row.Scan(
		&i.MaterialCode,
		&i.Description,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const plantSubSummaryMaterialPlant = `-- name: PlantSubSummaryMaterialPlant :one

SELECT
    pr.plant_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.plant_code    = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.plant_code    = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.plant_code
`

type PlantSubSummaryMaterialPlantParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type PlantSubSummaryMaterialPlantRow struct {
	PlantCode             string         `json:"plant_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctVendorCount   int64          `json:"distinct_vendor_count"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// D.2 MATERIAL + PLANT
// ============================================================
func (q *Queries) PlantSubSummaryMaterialPlant(ctx context.Context, arg PlantSubSummaryMaterialPlantParams) (PlantSubSummaryMaterialPlantRow, error) {
	row := q.db.QueryRowContext(ctx, plantSubSummaryMaterialPlant,
		arg.MaterialCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i PlantSubSummaryMaterialPlantRow
	err := row.Scan(
		&i.PlantCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctMaterialCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const plantSubSummaryMaterialVendorPlant = `-- name: PlantSubSummaryMaterialVendorPlant :one

SELECT
    pr.plant_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.vendor_code   = $2
       AND sub.plant_code    = $3
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.vendor_code   = $2
  AND pr.plant_code    = $3
  AND ($4::date IS NULL OR pr.purchase_date >= $4::date)
  AND ($5::date   IS NULL OR pr.purchase_date <= $5::date)
GROUP BY pr.plant_code
`

type PlantSubSummaryMaterialVendorPlantParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type PlantSubSummaryMaterialVendorPlantRow struct {
	PlantCode             string         `json:"plant_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctVendorCount   int64          `json:"distinct_vendor_count"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// D.4 MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) PlantSubSummaryMaterialVendorPlant(ctx context.Context, arg PlantSubSummaryMaterialVendorPlantParams) (PlantSubSummaryMaterialVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, plantSubSummaryMaterialVendorPlant,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i PlantSubSummaryMaterialVendorPlantRow
	err := row.Scan(
		&i.PlantCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctMaterialCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const plantSubSummaryPlant = `-- name: PlantSubSummaryPlant :one


SELECT
    pr.plant_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.plant_code = $1
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.plant_code = $1
  AND ($2::date IS NULL OR pr.purchase_date >= $2::date)
  AND ($3::date   IS NULL OR pr.purchase_date <= $3::date)
GROUP BY pr.plant_code
`

type PlantSubSummaryPlantParams struct {
	PlantCode string       `json:"plant_code"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type PlantSubSummaryPlantRow struct {
	PlantCode             string         `json:"plant_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctVendorCount   int64          `json:"distinct_vendor_count"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// SECTION D: PLANT SUB-SUMMARY QUERIES
// Returns per-plant aggregate metrics.
// Returned columns: plant_code, avg_cost, avg_net_price, last_purchase_cost,
//
//	min_cost, distinct_vendor_count, distinct_material_count,
//	purchase_order_count, currencies, units, earliest_date, latest_date
//
// ============================================================
// ============================================================
// D.1 PLANT ONLY
// ============================================================
func (q *Queries) PlantSubSummaryPlant(ctx context.Context, arg PlantSubSummaryPlantParams) (PlantSubSummaryPlantRow, error) {
	row := q.db.QueryRowContext(ctx, plantSubSummaryPlant, arg.PlantCode, arg.StartDate, arg.EndDate)
	var i PlantSubSummaryPlantRow
	err := row.Scan(
		&i.PlantCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctMaterialCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const plantSubSummaryVendorPlant = `-- name: PlantSubSummaryVendorPlant :one

SELECT
    pr.plant_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.vendor_code = $1
       AND sub.plant_code  = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.vendor_code)                                         AS distinct_vendor_count,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.vendor_code = $1
  AND pr.plant_code  = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.plant_code
`

type PlantSubSummaryVendorPlantParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

type PlantSubSummaryVendorPlantRow struct {
	PlantCode             string         `json:"plant_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctVendorCount   int64          `json:"distinct_vendor_count"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// D.3 VENDOR + PLANT
// ============================================================
func (q *Queries) PlantSubSummaryVendorPlant(ctx context.Context, arg PlantSubSummaryVendorPlantParams) (PlantSubSummaryVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, plantSubSummaryVendorPlant,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i PlantSubSummaryVendorPlantRow
	err := row.Scan(
		&i.PlantCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctVendorCount,
		&i.DistinctMaterialCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const summaryMaterial = `-- name: SummaryMaterial :one



SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE material_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type SummaryMaterialParams struct {
	MaterialCode string       `json:"material_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type SummaryMaterialRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// summary.sql
// Aggregate summary queries for each of the 7 filter combinations.
// Each query returns a single row with core aggregate metrics.
//
// Core metrics returned by all summary queries:
//
//	COUNT(*)                       AS records_found
//	SUM(cost)                      AS total_cost
//	AVG(cost)                      AS avg_cost
//	AVG(net_price)                 AS avg_net_price
//	MIN(cost)                      AS min_cost
//	MAX(cost)                      AS max_cost
//	COUNT(DISTINCT purchase_no)    AS purchase_order_count
//	MIN(purchase_date)             AS earliest_date
//	MAX(purchase_date)             AS latest_date
//	array_agg(DISTINCT currency)   AS currencies
//	array_agg(DISTINCT unit)       AS units
//
// Parameter layout mirrors counts.sql exactly:
//
//	Single-filter:  $1 = filter value; sqlc.narg('start_date'), sqlc.narg('end_date')
//	Two-filter:     $1, $2 = filter values; sqlc.narg('start_date'), sqlc.narg('end_date')
//	Three-filter:   $1 = material_code, $2 = vendor_code, $3 = plant_code; sqlc.narg dates
//
// Sub-summary queries provide per-entity breakdowns when a specific filter is present.
// "Last purchase cost" is retrieved via a correlated subquery ordered by purchase_date DESC.
//
// Requirements: 6.1, 6.2, 6.3, 6.4, 6.5, 6.6
// ============================================================
// SECTION A: CORE SUMMARY QUERIES (7 filter combinations × 2 date variants = 14)
// ============================================================
// ============================================================
// A.1 MATERIAL ONLY
// ============================================================
func (q *Queries) SummaryMaterial(ctx context.Context, arg SummaryMaterialParams) (SummaryMaterialRow, error) {
	row := q.db.QueryRowContext(ctx, summaryMaterial, arg.MaterialCode, arg.StartDate, arg.EndDate)
	var i SummaryMaterialRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryMaterialPlant = `-- name: SummaryMaterialPlant :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE material_code = $1
  AND plant_code    = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type SummaryMaterialPlantParams struct {
	MaterialCode string       `json:"material_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type SummaryMaterialPlantRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.5 MATERIAL + PLANT
// ============================================================
func (q *Queries) SummaryMaterialPlant(ctx context.Context, arg SummaryMaterialPlantParams) (SummaryMaterialPlantRow, error) {
	row := q.db.QueryRowContext(ctx, summaryMaterialPlant,
		arg.MaterialCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i SummaryMaterialPlantRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryMaterialVendor = `-- name: SummaryMaterialVendor :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type SummaryMaterialVendorParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type SummaryMaterialVendorRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.4 MATERIAL + VENDOR
// ============================================================
func (q *Queries) SummaryMaterialVendor(ctx context.Context, arg SummaryMaterialVendorParams) (SummaryMaterialVendorRow, error) {
	row := q.db.QueryRowContext(ctx, summaryMaterialVendor,
		arg.MaterialCode,
		arg.VendorCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i SummaryMaterialVendorRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryMaterialVendorPlant = `-- name: SummaryMaterialVendorPlant :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE material_code = $1
  AND vendor_code   = $2
  AND plant_code    = $3
  AND ($4::date IS NULL OR purchase_date >= $4::date)
  AND ($5::date   IS NULL OR purchase_date <= $5::date)
`

type SummaryMaterialVendorPlantParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type SummaryMaterialVendorPlantRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.7 MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) SummaryMaterialVendorPlant(ctx context.Context, arg SummaryMaterialVendorPlantParams) (SummaryMaterialVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, summaryMaterialVendorPlant,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i SummaryMaterialVendorPlantRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryPlant = `-- name: SummaryPlant :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE plant_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type SummaryPlantParams struct {
	PlantCode string       `json:"plant_code"`
	StartDate sql.NullTime `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type SummaryPlantRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.3 PLANT ONLY
// ============================================================
func (q *Queries) SummaryPlant(ctx context.Context, arg SummaryPlantParams) (SummaryPlantRow, error) {
	row := q.db.QueryRowContext(ctx, summaryPlant, arg.PlantCode, arg.StartDate, arg.EndDate)
	var i SummaryPlantRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryVendor = `-- name: SummaryVendor :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE vendor_code = $1
  AND ($2::date IS NULL OR purchase_date >= $2::date)
  AND ($3::date   IS NULL OR purchase_date <= $3::date)
`

type SummaryVendorParams struct {
	VendorCode string       `json:"vendor_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

type SummaryVendorRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.2 VENDOR ONLY
// ============================================================
func (q *Queries) SummaryVendor(ctx context.Context, arg SummaryVendorParams) (SummaryVendorRow, error) {
	row := q.db.QueryRowContext(ctx, summaryVendor, arg.VendorCode, arg.StartDate, arg.EndDate)
	var i SummaryVendorRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const summaryVendorPlant = `-- name: SummaryVendorPlant :one

SELECT
    COUNT(*)                        AS records_found,
    SUM(cost)                       AS total_cost,
    AVG(cost)                       AS avg_cost,
    AVG(net_price)                  AS avg_net_price,
    MIN(cost)                       AS min_cost,
    MAX(cost)                       AS max_cost,
    COUNT(DISTINCT purchase_no)     AS purchase_order_count,
    MIN(purchase_date)              AS earliest_date,
    MAX(purchase_date)              AS latest_date,
    array_agg(DISTINCT currency)    AS currencies,
    array_agg(DISTINCT unit)        AS units
FROM purchase_records
WHERE vendor_code = $1
  AND plant_code  = $2
  AND ($3::date IS NULL OR purchase_date >= $3::date)
  AND ($4::date   IS NULL OR purchase_date <= $4::date)
`

type SummaryVendorPlantParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

type SummaryVendorPlantRow struct {
	RecordsFound       int64       `json:"records_found"`
	TotalCost          int64       `json:"total_cost"`
	AvgCost            float64     `json:"avg_cost"`
	AvgNetPrice        float64     `json:"avg_net_price"`
	MinCost            interface{} `json:"min_cost"`
	MaxCost            interface{} `json:"max_cost"`
	PurchaseOrderCount int64       `json:"purchase_order_count"`
	EarliestDate       interface{} `json:"earliest_date"`
	LatestDate         interface{} `json:"latest_date"`
	Currencies         interface{} `json:"currencies"`
	Units              interface{} `json:"units"`
}

// ============================================================
// A.6 VENDOR + PLANT
// ============================================================
func (q *Queries) SummaryVendorPlant(ctx context.Context, arg SummaryVendorPlantParams) (SummaryVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, summaryVendorPlant,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i SummaryVendorPlantRow
	err := row.Scan(
		&i.RecordsFound,
		&i.TotalCost,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.MinCost,
		&i.MaxCost,
		&i.PurchaseOrderCount,
		&i.EarliestDate,
		&i.LatestDate,
		&i.Currencies,
		&i.Units,
	)
	return i, err
}

const vendorSubSummaryMaterialVendor = `-- name: VendorSubSummaryMaterialVendor :one

SELECT
    pr.vendor_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.vendor_code   = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.vendor_code   = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.vendor_code
`

type VendorSubSummaryMaterialVendorParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type VendorSubSummaryMaterialVendorRow struct {
	VendorCode            string         `json:"vendor_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	DistinctPlantCount    int64          `json:"distinct_plant_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// B.2 MATERIAL + VENDOR
// ============================================================
func (q *Queries) VendorSubSummaryMaterialVendor(ctx context.Context, arg VendorSubSummaryMaterialVendorParams) (VendorSubSummaryMaterialVendorRow, error) {
	row := q.db.QueryRowContext(ctx, vendorSubSummaryMaterialVendor,
		arg.MaterialCode,
		arg.VendorCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i VendorSubSummaryMaterialVendorRow
	err := row.Scan(
		&i.VendorCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctMaterialCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const vendorSubSummaryMaterialVendorPlant = `-- name: VendorSubSummaryMaterialVendorPlant :one

SELECT
    pr.vendor_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.material_code = $1
       AND sub.vendor_code   = $2
       AND sub.plant_code    = $3
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.material_code = $1
  AND pr.vendor_code   = $2
  AND pr.plant_code    = $3
  AND ($4::date IS NULL OR pr.purchase_date >= $4::date)
  AND ($5::date   IS NULL OR pr.purchase_date <= $5::date)
GROUP BY pr.vendor_code
`

type VendorSubSummaryMaterialVendorPlantParams struct {
	MaterialCode string       `json:"material_code"`
	VendorCode   string       `json:"vendor_code"`
	PlantCode    string       `json:"plant_code"`
	StartDate    sql.NullTime `json:"start_date"`
	EndDate      sql.NullTime `json:"end_date"`
}

type VendorSubSummaryMaterialVendorPlantRow struct {
	VendorCode            string         `json:"vendor_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	DistinctPlantCount    int64          `json:"distinct_plant_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// B.4 MATERIAL + VENDOR + PLANT
// ============================================================
func (q *Queries) VendorSubSummaryMaterialVendorPlant(ctx context.Context, arg VendorSubSummaryMaterialVendorPlantParams) (VendorSubSummaryMaterialVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, vendorSubSummaryMaterialVendorPlant,
		arg.MaterialCode,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i VendorSubSummaryMaterialVendorPlantRow
	err := row.Scan(
		&i.VendorCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctMaterialCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const vendorSubSummaryVendor = `-- name: VendorSubSummaryVendor :one


SELECT
    pr.vendor_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.vendor_code = $1
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.vendor_code = $1
  AND ($2::date IS NULL OR pr.purchase_date >= $2::date)
  AND ($3::date   IS NULL OR pr.purchase_date <= $3::date)
GROUP BY pr.vendor_code
`

type VendorSubSummaryVendorParams struct {
	VendorCode string       `json:"vendor_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

type VendorSubSummaryVendorRow struct {
	VendorCode            string         `json:"vendor_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	DistinctPlantCount    int64          `json:"distinct_plant_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// SECTION B: VENDOR SUB-SUMMARY QUERIES
// Returns per-vendor aggregate metrics.
// Returned columns: vendor_code, avg_cost, avg_net_price, last_purchase_cost,
//
//	min_cost, distinct_material_count, distinct_plant_count,
//	purchase_order_count, currencies, units, earliest_date, latest_date
//
// ============================================================
// ============================================================
// B.1 VENDOR ONLY
// ============================================================
func (q *Queries) VendorSubSummaryVendor(ctx context.Context, arg VendorSubSummaryVendorParams) (VendorSubSummaryVendorRow, error) {
	row := q.db.QueryRowContext(ctx, vendorSubSummaryVendor, arg.VendorCode, arg.StartDate, arg.EndDate)
	var i VendorSubSummaryVendorRow
	err := row.Scan(
		&i.VendorCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctMaterialCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}

const vendorSubSummaryVendorPlant = `-- name: VendorSubSummaryVendorPlant :one

SELECT
    pr.vendor_code,
    AVG(pr.cost)                                                           AS avg_cost,
    AVG(pr.net_price)                                                      AS avg_net_price,
    (SELECT sub.cost FROM purchase_records sub
     WHERE sub.vendor_code = $1
       AND sub.plant_code  = $2
     ORDER BY sub.purchase_date DESC, sub.id DESC LIMIT 1)                AS last_purchase_cost,
    MIN(pr.cost)                                                           AS min_cost,
    COUNT(DISTINCT pr.material_code)                                       AS distinct_material_count,
    COUNT(DISTINCT pr.plant_code)                                          AS distinct_plant_count,
    COUNT(DISTINCT pr.purchase_no)                                         AS purchase_order_count,
    array_agg(DISTINCT pr.currency)                                        AS currencies,
    array_agg(DISTINCT pr.unit)                                            AS units,
    MIN(pr.purchase_date)                                                  AS earliest_date,
    MAX(pr.purchase_date)                                                  AS latest_date
FROM purchase_records pr
WHERE pr.vendor_code = $1
  AND pr.plant_code  = $2
  AND ($3::date IS NULL OR pr.purchase_date >= $3::date)
  AND ($4::date   IS NULL OR pr.purchase_date <= $4::date)
GROUP BY pr.vendor_code
`

type VendorSubSummaryVendorPlantParams struct {
	VendorCode string       `json:"vendor_code"`
	PlantCode  string       `json:"plant_code"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

type VendorSubSummaryVendorPlantRow struct {
	VendorCode            string         `json:"vendor_code"`
	AvgCost               float64        `json:"avg_cost"`
	AvgNetPrice           float64        `json:"avg_net_price"`
	LastPurchaseCost      sql.NullString `json:"last_purchase_cost"`
	MinCost               interface{}    `json:"min_cost"`
	DistinctMaterialCount int64          `json:"distinct_material_count"`
	DistinctPlantCount    int64          `json:"distinct_plant_count"`
	PurchaseOrderCount    int64          `json:"purchase_order_count"`
	Currencies            interface{}    `json:"currencies"`
	Units                 interface{}    `json:"units"`
	EarliestDate          interface{}    `json:"earliest_date"`
	LatestDate            interface{}    `json:"latest_date"`
}

// ============================================================
// B.3 VENDOR + PLANT
// ============================================================
func (q *Queries) VendorSubSummaryVendorPlant(ctx context.Context, arg VendorSubSummaryVendorPlantParams) (VendorSubSummaryVendorPlantRow, error) {
	row := q.db.QueryRowContext(ctx, vendorSubSummaryVendorPlant,
		arg.VendorCode,
		arg.PlantCode,
		arg.StartDate,
		arg.EndDate,
	)
	var i VendorSubSummaryVendorPlantRow
	err := row.Scan(
		&i.VendorCode,
		&i.AvgCost,
		&i.AvgNetPrice,
		&i.LastPurchaseCost,
		&i.MinCost,
		&i.DistinctMaterialCount,
		&i.DistinctPlantCount,
		&i.PurchaseOrderCount,
		&i.Currencies,
		&i.Units,
		&i.EarliestDate,
		&i.LatestDate,
	)
	return i, err
}
