// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (employee_id, name, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, employee_id, name, role, created_at
`

type CreateUserParams struct {
	EmployeeID   string         `json:"employee_id"`
	Name         sql.NullString `json:"name"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
}

type CreateUserRow struct {
	ID         int64          `json:"id"`
	EmployeeID string         `json:"employee_id"`
	Name       sql.NullString `json:"name"`
	Role       string         `json:"role"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.EmployeeID,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_id, name, role
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         int64          `json:"id"`
	EmployeeID string         `json:"employee_id"`
	Name       sql.NullString `json:"name"`
	Role       string         `json:"role"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, employee_id, name, role, created_at, updated_at
FROM users
ORDER BY employee_id ASC
`

type ListUsersRow struct {
	ID         int64          `json:"id"`
	EmployeeID string         `json:"employee_id"`
	Name       sql.NullString `json:"name"`
	Role       string         `json:"role"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
